name: benv
channels:
- conda-forge
- defaults
dependencies:
- docutils=0.14=py36_0
- pip=9.0.1=py36_0
- pkginfo=1.4.1=py36_0
- python=3.6.3=1
- python-dateutil=2.6.1=py36_0
- requests=2.20.0=py36_1
- requests-toolbelt=0.8.0=py36_0
- setuptools=37.0.0=py36_0
- sphinx=1.6.5=py36_0
- sphinxcontrib-websupport=1.0.1=py36_0
- urllib3=1.22=py36_0
- virtualenv=15.1.0=py36_0
- vs2015_runtime=14.0.25420=0
- wheel=0.30.0=py_1
- win_inet_pton=1.0.1=py36_1
- yaml=0.1.7=vc14_0
- pip:
  - future==0.16.0
  - mypolr
  - pytest==3.3.0
  - responses==0.8.1
  - setuptools-scm==1.15.6
  - sphinx-argparse==0.2.1
  - sphinx-rtd-theme==0.2.4
  - tox==2.9.1
  - tox-with-conda
prefix: E:\Anaconda3\envs\benv

